apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # (Can be claimed as Read and Write by only one node)
    # - ReadOnlyMany (Can be claimed as Read only by many nodes)
    # - ReadWriteMany (Can be claimed as Read and Write by multiple nodes)
  hostPath:
    path: /data
    type: DirectoryOrCreate